### ISSUE TITLE
mem_sleep_default=deep has a fix

### ISSUE THREAD

**Issue by smopucilowski** [delta-one/dell-xps-15-9570#2]
You may now use the `mem_sleep_default=deep` kernel parameter for deep sleeping.

According to:
https://wiki.archlinux.org/index.php/Dell_XPS_15_9570 and
https://www.dell.com/community/Precision-Mobile-Workstations/High-load-heating-up-fan-noise-after-S3-suspend-and-resume-on/td-p/7441933
clicking the touchpad pulls the CPU out of a high power state if it gets stuck, likely an IRQ triggering it.

**Comment by delta-one** [comment]
Thanks for the tip. I'll test it and update the description if needed.

**Comment by delta-one** [comment]
I tested it again and I didn't have the CPU bug anymore. There was no need to click the touchpad.

However, the deep sleep seems to screw some of my energy settings. The hardware buttons for setting the brightness or for turning the screen on/off don't work anymore after a deep sleep. Have you noticed anything lke that ?

**Comment by smopucilowski** [comment]
No, I've noticed no such issues; I'm using mate-desktop however, which uses mate-power-manager which takes over power management when the graphical session is running.

**Comment by delta-one** [comment]
Tried it again and this time, it was the exact opposite: Energy fn-buttons were fine, but the CPU got stuck. Clicking on the touchpad resolved the issue though. I'll update the description. Thanks for reporting it.
