### ISSUE TITLE
Keyboard surface is warm

### ISSUE THREAD

**Issue by MarianaPicolo** [delta-one/dell-xps-15-9570#3]
Hello, I've followed your tutorial, and managed to install Debian testing on my XPS :)

But, I have some points that I'd like to note:
 - As you can see on the issue's title: now I notice my keyboard's surface slightly warmer than the normal. "Normal", I think, because I've never noticed that on Ubuntu, for example. (NVIDIA is off, and powertop is enabled with `auto-tune`);
This happens with the battery plugged or unplugged, it doesn't matter. And it happens when the computer is on idle, with only the browser opened with 5 tabs.

Also, powertop shows this discharge rate when my computer in only with the browser and some tabs opened: `The battery reports a discharge rate of 9.24 W`

- My mouse is slow. If I don't use the mouse for a while, when I move it again, the "wake up" is slow, it's a kind of delay, I don't know; This doesn't happen with the touchpad, though.
- I've had some screen flickering, and managed to fix with [this](https://wiki.archlinux.org/index.php/intel_graphics#Screen_flickering).

**Edit**:
I'm also experiencing some random freezes. I noticed that it happens when I'm using docker. The cursor doesn't move anymore, but the music in background keeps playing.
Here's my system info: `Linux xps-9570 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
`

**Comment by delta-one** [comment]
Hej Mariana,

thanks for raising those issues.

* The XPS 15 does unfortunately not have a good thermal design, which sadly results in rather high temperatures. Have you checked the CPU temperature, when your keyboard is getting warm ?
* I noticed those mouse-delays *after* I had run `powertop --auto-tune` but never really before. It could be that powertop puts the USB ports into a power-saving mode thus delaying the input. Try fiddling with the powertop-settings and see, if the issue improves.
* I also noticed some screen flickering especially when starting KDE Plasma. Usually it settled very soon, so I never really bothered fixing it. After adding the kernel-parameter `i915.enable_psr=0` the situation improved clearly. I've updated the corresponding section.
* I don't use Docker, so I cannot reproduce the issue. Do you have any more logs ?

**Comment by MarianaPicolo** [comment]
>     * The XPS 15 does unfortunately not have a good thermal design, which sadly results in rather high temperatures. Have you checked the CPU temperature, when your keyboard is getting warm ?

I'm trying to monitor, but it seems normal:
|Laptop was just turned on, it was cold | After some hours of usage |
|:---:|:---:|
|![Captura de tela de 2020-04-13 14-08-50](https://user-images.githubusercontent.com/26073710/79175015-dea23d00-7dd2-11ea-8cca-31c40b95b19a.png)|![Captura de tela de 2020-04-13 16-27-42](https://user-images.githubusercontent.com/26073710/79175038-f24da380-7dd2-11ea-94b5-42cc6335da97.png)|

>     * I noticed those mouse-delays _after_ I had run `powertop --auto-tune` but never really before. It could be that powertop puts the USB ports into a power-saving mode thus delaying the input. Try fiddling with the powertop-settings and see, if the issue improves.

I've just checked on powertop stats, and that the issue, the setting to the autosuspend is on, when I turn it bad, the mouse delay is gone.    

![image](https://user-images.githubusercontent.com/26073710/79175231-84ee4280-7dd3-11ea-930b-45b49e223d52.png)

>     * I don't use Docker, so I cannot reproduce the issue. Do you have any more logs ?  

Unfortunately, I don't. It happens randomly, sometimes it takes a few hours to happen, and sometimes it takes 20 minutes after the boot. I noticed that it happens when I run docker, but I've seen in some forums that it happens when the HDMI gets disconnected from the laptop.   

I've been searching on this problem, it seems like is with this kernel version: https://linuxreviews.org/Linux_Kernel_5.5_Will_Not_Fix_The_Frequent_Intel_GPU_Hangs_In_Recent_Kernels

https://www.reddit.com/r/archlinux/comments/e7tb8i/intel_i915_random_freeze/

I've added this parameters to the grub: `iommu=pt intel_idle.max_cstate=1`, but I'm not sure about what they do. At this moment my laptop hasn't frozen yet.

**Comment by delta-one** [comment]
* Your temperatures seem a bit high. When my CPU is more or less idle (but with several programms opened), the temperature is often between 36-40C without any fan turned on. If the fans are on, then the temperature hovers between 30-35C or so. I don't know why your temperatures are so high, maybe undervolting helps, maybe your thermal system is a bit clogged. This is after running several hours:
![Screenshot_20200414_141344](https://user-images.githubusercontent.com/9049025/79223984-9f1f3380-7e5a-11ea-81c2-ce015ed44aa4.png)

* CPUs have different power modes/states and these states are called C-states. C0 is the normal operating mode and the higher the number goes, the "deeper" the CPU sleeps in order to save energy. If you limit the CPU to C0/C1, you're preventing the CPU from entering these low-power states and should in theory have a higher battery consumption. powertop gives you a stat saying how much time the CPU spends in which state. I've read about system freezes, when the CPU is in a too deep state, but I don't think that it's specific to the XPS 15. But feel free to experiment and report back.

**Comment by MarianaPicolo** [comment]
This is also one thing I've noticed: my fans are on even on idle state, with these temperatures. I think that's why the keyboard area is getting warmer.   
I've never noticed that on ubuntu. It was my distro before I switch to debian testing, because I thought it was easier to deal with nvidia.
